papers = [
    ["https://www.theguardian.com/uk", "The Guardian", "span", "js-headline-text", 20, "guardian"],
    ["https://www.mirror.co.uk/", "Mirror", "h2", "story__title", 19, "mirror"],
    ["https://www.thetimes.co.uk/", "The Times", "h3", "Headline--xl", 18, "times"],
    ["https://www.thesun.co.uk/", "The Sun", "h2", "nk-headline-heading css-1r6h6ly", 17, "sun"],
    ["https://www.independent.co.uk/", "Independent", "a", "title", 16, "indy"],
    ["https://www.ft.com/world/uk", "Financial Times", "div", "o-teaser__heading", 15, "ft"],
    ["https://www.telegraph.co.uk/", "The Telegraph", "span", "list-headline__text", 14, "telegraph"],
    ["https://www.express.co.uk/", "Express", "h2", "", 13, "express"],
    ["https://metro.co.uk/", "METRO", "span", "colour-box", 12, "metro"],
    ["https://www.standard.co.uk/news/uk", "Evening Standard", "a", "title", 11, "standard"],
    ["https://www.cityam.com/", "City A.M.", "h3", "card__title", 10, "cityam"],
    ["https://www.dailystar.co.uk/", "Daily Star", "a", "publication-font", 9, "star"],
    ["https://morningstaronline.co.uk/", "Morning Star", "div", "top-story", 8, "morning"],
    ["https://www.thesun.ie/", "The Irish Sun", "h2", "nk-headline-heading css-1r6h6ly", 7, "irishsun"],
    ["https://www.heraldscotland.com/", "The Herald", "a", "mar-lead-story__link", 6, "herald"],
    ["https://www.dailymail.co.uk/home/index.html", "Mail Online", "h2", "linkro-darkred", 5, "mail"],
    ["https://www.dailyrecord.co.uk", "Daily Record", "a", "headline publication-font", 4, "record"],
    ["https://www.irishtimes.com", "Irish Times", "a", "text_decoration_none color_custom_black_1", 3, "irishtimes"],
    ["https://www.irishexaminer.com", "Irish Examiner", "h5", "card-title top-main-title", 2, "irishexaminer"],
    ["https://www.irishpost.com", "Irish Post", "h2", "", 1, "irishpost"],
]